version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=resume_analyzer
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
